apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  containers:
  - name: simple-webapp-mysql
    image: kodekloud/simple-webapp-mysql
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
